import './js/support-create';
import './js/shopping-list';
import './js/shopingAut';
import './js/themes';
import './js/burgerModal';
// import './js/shop-list-make-markup';
// import './js/delete-book-firebase';
import './js/local-storage';
import './js/pagination';
import './js/pagination-btn';
